import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// --- Our Imports ---
import { AuthProvider } from "@/context/AuthContext";
// -----------------

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Affectra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* --- Wrap children with AuthProvider --- */}
        <AuthProvider>
          {children}
        </AuthProvider>
        {/* -------------------------------------- */}
      </body>
    </html>
  );
}